language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.npm
    - node_modules
  npm: true
  bundler: true
notifications:
  email: false
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
branches:
  only:
    - develop
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
before_install:
  # package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g github-label-sync
install:
  - travis_retry npm install
  - travis_retry bundle install
script:
  - travis_retry github-label-sync -a "$GH_TOKEN" -l 'https://git.io/fAe5i' seantrane/seantrane.github.io
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
  # - bundle exec htmlproofer ./site --disable-external
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  name: Sean Trane
  email: seantrane@users.noreply.github.com
  keep-history: true
  target-branch: master
  local-dir: ./site
  on:
    repo: seantrane/seantrane.github.io
    branch: develop
