source 'https://rubygems.org'
source 'http://gems.github.com'
gem 'github-pages'
gem 'kramdown'
gem 'netrc'
# gem 'redcarpet'
group :jekyll_plugins do
  gem 'jekyll-email-protect'
  gem 'jekyll-gist'
  gem 'jekyll-github-metadata'
  gem 'jekyll-paginate'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jekyll-toc'
  gem 'jekyll-youtube'
  gem 'jemoji'
end
